import { getChatResponse } from '../../../lib/openai';

export async function POST(request) {
  const { message } = await request.json();

  const healthKeywords = [
    "symptom","feeling","tired","covid-19","covid","symptoms","feel", 
    "illness", "disease", "health", "condition", "head","teeth",
    "eyes","nose","ears","tongue","hands","feet","mouth","bones","bone",
    "pain", "fever", "cough", "headache", "stomachache", 
    "infection", "virus", "bacteria", "flu", "cold", "rash",
    "nausea", "vomiting", "diarrhea", "chills", "sweating", 
    "fatigue", "weakness", "dizziness", "shortness of breath", 
    "chest", "throat", "muscle", "ache", "joint", 
    "pain", "sinusitis", "congestion", "runny nose", 
    "sneeze", "itchiness", "allergy", "asthma", "bronchitis", 
    "pneumonia", "tuberculosis", "tb", "hepatitis", "cancer", "tumor", 
    "ulcer", "arthritis", "eczema", "psoriasis", "migraine", 
    "stroke", "seizure", "epilepsy", "diabetes", "hypertension", 
    "hypotension", "anemia", "leukemia", "hemorrhage", 
    "bleeding", "blood", "dysentery", "malaria", "chronic", "acute", 
    "gastroenteritis", "jaundice", "cirrhosis", "kidney stones", 
    "gout", "tendinitis", "sciatica", "neuralgia", "meningitis", 
    "encephalitis", "cystitis", "vaginitis", "prostatitis", 
    "pelvic inflammatory disease", "chlamydia", "gonorrhea", 
    "syphilis", "herpes", "human papillomavirus", "hiv", 
    "aids", "tetanus", "rabies", "cholera", "typhoid", 
    "rheumatism", "fibromyalgia", "lupus", "scleroderma", 
    "vitiligo", "alopecia", "hyperthyroidism", "hypothyroidism", 
    "Addison's disease", "syndrome", "Graves' disease", 
    "Parkinson's disease", "Alzheimer", "dementia", 
    "multiple sclerosis", "amyotrophic lateral sclerosis", 
    "muscular dystrophy", "spina bifida", "hydrocephalus", 
    "epidermolysis bullosa", "cystic fibrosis", "sickle cell anemia", 
    "thalassemia", "hemophilia", "von Willebrand disease", 
    "thrombosis", "embolism", "atherosclerosis", "myocarditis", 
    "pericarditis", "endocarditis", "arrhythmia", "tachycardia", 
    "bradycardia", "heart", "lungs", "myocardial infarction", 
    "angina", "varicose veins", "phlebitis", "chronic", "obstructive", "pulmonary", 
    "emphysema", "bronchitis", "embolism", 
    "pleurisy", "lung", "mesothelioma", "pneumothorax", 
    "hydrothorax", "pleural effusion", "asbestosis", 
    "silicosis", "sarcidosis", "interstitial lung disease", 
    "tuberculosis", "bronchiectasis", "pneumoconiosis", 
    "acute respiratory distress syndrome", "sleep", 
    "snoring", "insomnia", "narcolepsy", "restless", "legs", "syndrome", 
    "parasomnia", "somnambulism", "night terrors", "nightmares", 
    "obstructive sleep apnea", "central sleep apnea", "complex sleep apnea", 
    "sleepwalking", "REM sleep behavior disorder", "hypersomnia", 
    "delirium", "hallucination", "psychosis", "schizophrenia", 
    "bipolar disorder", "depression", "anxiety", "panic", "attack", 
    "obsessive-compulsive disorder", "post-traumatic", "stress", "disorder", 
    "eating disorder", "anorexia", "bulimia", "binge eating disorder", 
    "autism spectrum disorder", "attention deficit hyperactivity disorder", 
    "personality disorder", "borderline personality disorder", 
    "narcissistic personality disorder", "antisocial personality disorder", 
    "paranoid personality disorder", "histrionic personality disorder", 
    "avoidant personality disorder", "dependent personality disorder", 
    "schizoid personality disorder", "schizotypal personality disorder", 
    "mental retardation", "intellectual disability", "learning disability", 
    "dyslexia", "dysgraphia", "dyscalculia", "speech disorder", 
    "language disorder", "aphasia", "apraxia", "dysarthria", 
    "voice disorder", "stuttering", "stammering", "articulation disorder", 
    "fluency disorder", "hearing loss", "deafness", "tinnitus", 
    "ear infection", "otitis media", "otitis externa", "vertigo", 
    "Meniere's disease", "Eustachian tube dysfunction", "meningitis", 
    "encephalopathy", "encephalitis", "encephalomyelitis", 
    "neuropathy", "myopathy", "neuromuscular disease", "brain tumor", 
    "spinal cord injury", "cerebral palsy", "stroke", "transient ischemic attack", 
    "TIA", "aneurysm", "arteriovenous malformation", "cerebral hemorrhage", 
    "subdural hematoma", "epidural hematoma", "intracerebral hemorrhage", 
    "subarachnoid hemorrhage", "concussion", "contusion", "brain injury", 
    "traumatic brain injury", "spinal cord injury", "herniated disc", 
    "scoliosis", "kyphosis", "lordosis", "spinal stenosis", 
    "degenerative disc disease", "vertebral fracture", "compression fracture", 
    "osteoporosis", "osteopenia", "paget's disease", "bone cancer", 
    "bone infection", "osteomyelitis", "chondrosarcoma", 
    "sarcoma", "rhabdomyosarcoma", "leukemia", "lymphoma", 
    "Hodgkin's lymphoma", "non-Hodgkin's lymphoma", "myeloma", 
    "neuroblastoma", "retinoblastoma", "Wilms' tumor", "testicular cancer", 
    "ovarian cancer", "cervical cancer", "endometrial cancer", 
    "breast", "cancer", "prostate cancer", "skin cancer", 
    "melanoma", "basal cell carcinoma", "squamous cell carcinoma", 
    "keratosis", "actinic keratosis", "seborrheic keratosis", 
    "sunburn", "burn", "chemical burn", "electrical burn", 
    "radiation burn", "superficial burn", "partial-thickness burn", 
    "full-thickness burn", "burn injury", "trauma", "accident", 
    "injury", "fracture", "dislocation", "sprain", "strain", 
    "contusion", "laceration", "abrasion", "puncture", 
    "penetrating injury", "crush injury", "amputation", "disfigurement", 
    "post-surgical pain", "chronic pain", "acute pain", "phantom pain", 
    "neuropathic pain", "nociceptive pain", "visceral pain", 
    "somatic pain", "pain management", "pain relief", 
    "analgesia", "anesthesia", "local anesthesia", "general anesthesia", 
    "regional anesthesia", "spinal anesthesia", "epidural anesthesia", 
    "block anesthesia", "painkiller", "opioid", "narcotic", 
    "nonsteroidal anti-inflammatory drug", "NSAID", "acetaminophen", 
    "ibuprofen", "aspirin", "naproxen", "celecoxib", "tramadol", 
    "codeine", "morphine", "oxycodone", "hydrocodone", "fentanyl", 
    "methadone", "buprenorphine", "naloxone", "naltrexone", 
    "buprenorphine-naloxone", "suboxone", "heroin", "cocaine", 
    "methamphetamine", "amphetamine", "hallucinogen", "stimulant", 
    "depressant", "sedative", "antidepressant", "anxiolytic", 
    "antipsychotic", "mood stabilizer", "anticonvulsant", "antihistamine", 
    "antibiotic", "antiviral", "antifungal", "antiparasitic", 
    "antiseptic", "antacid", "laxative", "diuretic", "bronchodilator", 
    "cough suppressant", "expectorant", "antitussive", "vasodilator", 
    "antihypertensive", "antiarrhythmic", "anticoagulant", "antiplatelet", 
    "lipid-lowering agent", "statin", "beta-blocker", "ACE inhibitor", 
    "ARB", "calcium channel blocker", "diuretic", "proton pump inhibitor", 
    "H2 blocker", "antidiabetic", "insulin", "sulfonylurea", "metformin", 
    "thiazolidinedione", "GLP-1 receptor agonist", "DPP-4 inhibitor", 
    "SGLT2 inhibitor", "glucagon", "somatostatin", "growth hormone", 
    "thyroid hormone", "estrogen", "progesterone", "testosterone", 
    "adrenaline", "noradrenaline", "cortisol", "epinephrine", 
    "norepinephrine", "insulin", "glucagon", "oxytocin", 
    "prolactin", "aldosterone", "melatonin", "calcitonin", 
    "parathyroid hormone", "erythropoietin", "vasopressin", 
    "antiemetic", "antidiarrheal", "antitussive", "antispasmodic", 
    "anticonvulsant", "antiparkinsonian", "antiemetic", "antihypertensive", 
    "antidiabetic", "anticoagulant", "anti-inflammatory", "analgesic", 
    "antidepressant", "anxiolytic", "sedative", "stimulant", 
    "antipsychotic", "mood stabilizer", "antihistamine", "antiviral", 
    "antibiotic", "antifungal", "antiparasitic", "antiseptic", 
    "antacid", "laxative", "diuretic", "bronchodilator", 
    "cough suppressant", "expectorant", "vasodilator", "beta-blocker", 
    "ACE inhibitor", "ARB", "calcium channel blocker", 
    "statin", "proton pump inhibitor", "H2 blocker", "insulin", 
    "metformin", "sulfonylurea", "thiazolidinedione", 
    "GLP-1 receptor agonist", "DPP-4 inhibitor", "SGLT2 inhibitor", 
    "glucagon", "growth hormone", "thyroid hormone", "estrogen", 
    "progesterone", "testosterone", "adrenaline", "noradrenaline", 
    "cortisol", "epinephrine", "norepinephrine", "oxytocin", 
    "prolactin", "aldosterone", "melatonin", "calcitonin", 
    "parathyroid hormone", "erythropoietin", "vasopressin", 
    "hypoglycemia", "hyperglycemia", "glycemic index", 
    "glycemic load", "ketoacidosis", "hypoparathyroidism", 
    "hyperparathyroidism", "hypogonadism", "hypergonadism", 
    "hypercalcemia", "hypocalcemia", "hypernatremia", "hyponatremia", 
    "hyperkalemia", "hypokalemia", "hyperuricemia", "hypouricemia", 
    "hyperlipidemia", "hypolipidemia", "hypoxemia", "hyperoxemia", 
    "hypothermia", "hyperthermia", "heat stroke", "heat exhaustion", 
    "cold stress", "frostbite", "hypothermia", "hyperthermia", 
    "hyperventilation", "hypoventilation", "atelectasis", 
    "lung fibrosis", "respiratory alkalosis", "respiratory acidosis", 
    "metabolic alkalosis", "metabolic acidosis", "alkalosis", 
    "acidosis", "respiratory failure", "cardiac arrest", "cardiac tamponade", 
    "heart murmur", "angina pectoris", "coronary artery disease", 
    "myocardial ischemia", "ventricular fibrillation", 
    "ventricular tachycardia", "atrial fibrillation", "atrial flutter", 
    "supraventricular tachycardia", "bradyarrhythmia", 
    "tachyarrhythmia", "cardiomyopathy", "endocarditis", 
    "pericarditis", "myocarditis", "chronic heart failure", 
    "left-sided heart failure", "right-sided heart failure", 
    "congestive heart failure", "acute coronary syndrome", 
    "unstable angina", "stable angina", "unstable angina", 
    "stable angina", "myocardial infarction", "non-ST elevation MI", 
    "ST elevation MI", "heart block", "bundle branch block", 
    "atrioventricular block", "sick sinus syndrome", "coronary spasm", 
    "prinzmetal angina", "infarct", "cardiac rehabilitation", 
    "angioplasty", "stent placement", "coronary artery bypass grafting", 
    "CABG", "percutaneous coronary intervention", "PCI", 
    "cardiac catheterization", "echocardiogram", "electrocardiogram", 
    "ECG", "Holter monitor", "event monitor", "cardiac MRI", 
    "cardiac CT scan", "stress test", "nuclear stress test", 
    "treadmill test", "dobutamine stress test", "stress echocardiogram", 
    "cardiac enzyme tests", "troponin", "CK-MB", "BNP", 
    "C-reactive protein", "D-dimer", "electrolytes", 
    "blood gas analysis", "lactic acid", "BUN", "creatinine", 
    "urinalysis", "urine culture", "urine test strip", 
    "microscopic urinalysis", "24-hour urine collection", 
    "urine protein", "urine glucose", "urine ketones", 
    "urine bilirubin", "urine pH", "urine specific gravity", 
    "urine osmolality", "urine electrolytes", "hemoglobin A1c", 
    "fasting blood glucose", "postprandial blood glucose", 
    "oral glucose tolerance test", "blood lipid profile", 
    "cholesterol", "triglycerides", "LDL", "HDL", "total cholesterol",
  ];
    function containsHealthKeywords(paragraph) {
        const lowerCaseParagraph = paragraph.toLowerCase();

        for (const keyword of healthKeywords) {
            if (lowerCaseParagraph.includes(keyword)) {
                return true;  
            }
        }
        return false; 
    }
  if (containsHealthKeywords(message) ) {
    try {
      const reply = await getChatResponse(message);
      return new Response(JSON.stringify({ reply }), { status: 200 });
    } catch (error) {
      return new Response(JSON.stringify({ error: 'Error fetching response from AI API' }), { status: 500 });
    }
  } else {
    const reply = "I'm a symptom checker bot and I can help you with health and illness related information. If you're interested in any health symptoms, or learning about health, feel free to ask!";
    return new Response(JSON.stringify({ reply }), { status: 200 });
  }
}
